### ISSUE TITLE
Project 7 - Using Bootstrap

### ISSUE THREAD

**Issue by abongsjoel** [vichuge/7-using-bootstrap#2]
This issue is created for the code review of one of the team members of team-161 the palms

**Comment by MrkarlosM** [comment]
You should use `d-flex align-items-end` to put the login part of the nav bar.

https://getbootstrap.com/docs/4.4/utilities/flex/

Also, try to avoid using `nav-bar` and other nonrelated classes in a row element. If you can create another `div`, go for it.
